"""update contact table schema

Revision ID: 2ea679734aab
Revises: f7eebafac0f9
Create Date: 2026-02-08 22:26:35.032835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea679734aab'
down_revision = 'f7eebafac0f9'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('status')
        batch_op.drop_column('country')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
